[tool.poetry]
name = "microscopemetrics"
version = "0.2.2"
description = "A package providing analysis routines to measure the performance of micrsocopes used in biomedical research"
authors = [
    "Julio Mateos Langerak <julio.matoes-langerak@igh.cnrs.fr>",
    "Sotirios Papadiamantis <sotirios.papadiamantis@univ-amu.fr>"
]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/MontpellierRessourcesImagerie/microscope-metrics"
repository = "https://github.com/MontpellierRessourcesImagerie/microscope-metrics"
documentation = "https://github.com/MontpellierRessourcesImagerie/microscope-metrics/tree/master/docs"
keywords = ["microscopy", "metrology"]

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[tool.poetry.dependencies]
python = ">=3.8 <=3.11"
scikit-image = "^0.19.3"
scipy = "^1.5.4"
pandas = "^1.1.5"
matplotlib = "^3.7.1"
microscopemetrics-schema = {git = "https://github.com/MontpellierRessourcesImagerie/microscopemetrics-schema.git", branch = "py38"}

[tool.poetry.group.test.dependencies]
pytest = "^6.2.0"
tox = "^3.26.0"
coverage = "^7.3.1"

[tool.poetry.group.dev.dependencies]
blacked = "^0.1.0-alpha.4"
poetry = "^1.2.2"
jupyter = "^1.0.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
