[tool.poetry]
name = "microscopemetrics"
version = "0.1.0"
description = "A package providing analysis routines to measure the performance of micrsocopes used in biomedical research"
authors = ["Julio Mateos Langerak <julio.matoes-langerak@igh.cnrs.fr>"]
license = "GPL-3.0-only"

[tool.pytest.ini_options]
addopts = "--cov=microscope-metrics"
testpaths = [
    "tests/unit"
]

[tool.tox]
legacy_tox_ini = """
[tox]
requires = tox-poetry-dev-dependencies
envlist = py38, py39, py310

[testenv]
poetry_add_dev_dependencies = True
commands = pytest
"""

[tool.poetry.dependencies]
python = ">=3.8 <3.10"
scikit-image = "^0.19.3"
scipy = "^1.5.4"
pandas = "^1.1.5"
pydantic = "^1.7.3"

[tool.poetry.dev-dependencies]
blacked = "^0.1.0-alpha.4"
poetry = "^1.1.4"
pytest = "^6.2.0"
pytest-cov = "^4.0.0"
jupyter = "^1.0.0"
tox = "^3.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
